### ISSUE TITLE
可以尝试将部分dts推到主线内核

### ISSUE THREAD

**Issue by wangling12** [unifreq/linux-5.13.y#2]
例如我正用的x96

**Comment by unifreq** [comment]
不会，感觉好复杂，要写英文邮件发自我的华为手机-------- 原始邮件 --------发件人： wangling12 ***@***.***>日期： 2021年8月14日周六 21:18收件人： "unifreq/linux-5.13.y" ***@***.***>抄送： Subscribed ***@***.***>主    题： [unifreq/linux-5.13.y] 可以尝试将部分dts推到主线内核 (#2)

例如我正用的x96

**Comment by wangling12** [comment]
> 不会，感觉好复杂，要写英文邮件

不复杂，基本上就是按功能拆分patch，然后简单描述一下，英语部分就交给百度翻译吧，最后amlogic的往这发邮件:
http://lists.infradead.org/mailman/listinfo/linux-amlogic

---
简易版教程https://linux.cn/article-10109-1.html
完整版本https://www.kernel.org/doc/html/latest/process
估计只需要仔细看这一节https://www.kernel.org/doc/html/latest/process/5.Posting.html

**Comment by wangling12** [comment]
对了，amlogic的内核树应该是这个https://git.kernel.org/pub/scm/linux/kernel/git/amlogic/linux.git
